app = "cursor-demo-db"
primary_region = "ams"

[build]
  image = "postgres:15-alpine"

[env]
  POSTGRES_PASSWORD = "postgres"  # Simple dev password
  POSTGRES_USER = "postgres"
  POSTGRES_DB = "cursor_demo_dev"  # Changed to dev database

[[mounts]]
  source = "postgres_data"
  destination = "/var/lib/postgresql/data"

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 