app = "cursor-demo"
primary_region = "ams"
kill_signal = "SIGTERM"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["phoenix-static"]

[env]
  PHX_HOST = "cursor-demo.fly.dev"
  PORT = "8080"
  DATABASE_URL = "ecto://postgres:postgres@cursor-demo-db.internal:5432/cursor_demo_dev"
  SECRET_KEY_BASE = "development_secret_key_base"
  RELEASE_COOKIE = "development_cookie"

[deploy]
  release_command = "/app/bin/migrate"
  strategy = "bluegreen"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

[[statics]]
  guest_path = "/app/priv/static"
  url_prefix = "/assets"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 