app = "cursor-demo"
primary_region = "ams" # Amsterdam, change this to your preferred region

[build]
  [build.args]
    BUILD_WITH_DEV=false

[env]
  PHX_HOST = "cursor-demo.fly.dev"
  PORT = "8080"
  DATABASE_PATH = "/data/cursor_demo.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source="cursor_demo_data"
  destination="/data" 